### PR TITLE
Add website and repository for npmjs.com

### PR DESCRIPTION
**Pull request by karlhorky**
Add `website` and `repository` references to be used on [npmjs.com](https://www.npmjs.com/package/@hackbg/ubik)

### CODE REVIEW

**Comment by egasimus** [comment]
Thanks!

**Comment by karlhorky** [comment]
Glad to help, thanks for the review and merge :)

To get this appearing on npmjs.com you'll need to publish a new version.

**Comment by egasimus** [comment]
Sure thing, I just need to find a spare moment to figure out how v1.4.0 ended up falling off the main branch [^0]:

Screenshot from 2023-07-09 22-14-22

I don't feel completely comfortable publishing a new version without resolving that potential regression first. If you'd like to lend a hand with that, I'd be happy to merge and publish the result :-)

[^0]: For the record, it's probably because we also consume these libraries as Git submodules

**Comment by egasimus** [comment]
`@hackbg/ubik 1.4.1` published :tada: 

Screenshot from 2023-07-14 23-17-03

**Comment by karlhorky** [comment]
Great, thanks!

**Pull request merged**
